Feature/admin panel students
peaksoft-school/peaksoft-lms-a-web pull request #27
Opened 2022-05-19 16:09 UTC by ric1709

2022-05-20 15:38 UTC, zhumabek requested changes

2022-05-20 15:38 UTC, zhumabek commented on src/components/Admin/Students/Students.jsx
> +   const groupOptions = [
useMemo го салып кой да

2022-05-20 15:38 UTC, zhumabek commented on src/components/Admin/Students/Students.jsx
> +   const COLUMNS = [
useMemo салып койсон болот

2022-05-21 11:08 UTC, ric1709 commented on src/components/Admin/Students/Students.jsx
> +      dispatch(getGroups())
I thought firstly user should choose to which group he/she will add students

2022-05-22 08:49 UTC, zhumabek requested changes

2022-05-22 08:49 UTC, zhumabek commented on src/components/Admin/Students/Students.jsx
>        setTimeout(() => {
бул жерде  setTimeout эмне кызматты аткарып жатат?
получается каждый notification modal коргозуп очуруш учун ушундай кылып жазыш керекби ээ? вообще жаккан жок мага бул решение

2022-05-22 08:49 UTC, zhumabek commented on src/components/Admin/Students/Students.jsx
> +         {successMessage && <Notification message={successMessage} />}
эмнеге условный оператор колдонуп жатасынар? башкаларга дагы айтып койчу ондош керек

2022-05-22 08:49 UTC, zhumabek commented on src/components/Admin/Students/Students.jsx
> +         {successMessage && <Notification message={successMessage} />}
<Notification message={successMessage} isOpen={true | false}/>
же атайын билиотекалар бар ошолрду колдонгула
азыркы решение мага такыр жаккан жок
не практично

2022-05-22 08:49 UTC, zhumabek commented on src/components/Admin/Students/StudentsModalForm.jsx
> +               options={groups[0]}
почему нулевой индекс? не понятно

2022-05-22 10:19 UTC, ric1709 commented on src/components/Admin/Students/StudentsModalForm.jsx
> +               options={groups[0]}
groups.map((el) => {
            return {
               id: el.id,
               title: el.groupName,
            }
         }),
i need groups name and id to give them to select as an option 
And after map they are  in 0th index of an array

2022-05-23 05:54 UTC, zhumabek requested changes

2022-05-23 05:54 UTC, zhumabek commented on src/components/Admin/Students/Students.jsx
> +         <Notification
все равно не нравиться

я хочу чтобы я мог вызвать функцию showSuccessMesssage('Success') и  showErrorMessage('dfjbvjdf dfcdfcd') 

без jsx  кода `<Notification
            message={error}
            status="error"
            onClose={closeNotification}
            open={openErrorNotification}
         />`

2022-05-23 13:10 UTC, zhumabek commented on src/components/Admin/Students/Students.jsx
> +         <Notification />
может   App.js ке эле коюп коюш керек? анткени глобальный компонент да ээ? документацияны окудун беле?

2022-05-23 13:32 UTC, merged