Feature/course admin panel
peaksoft-school/peaksoft-lms-a-web pull request #28
Opened 2022-05-21 05:58 UTC by mavliuda19

2022-05-21 09:54 UTC, zhumabek requested changes

2022-05-21 09:54 UTC, zhumabek commented on src/components/admin/courses/AddNewCourse.jsx
> +
А что если не удалось сохранить файл? Запрос не успешный болуп калды десекчи: ошондо деле модалканы жаап саласынбы?

2022-05-21 09:54 UTC, zhumabek commented on src/components/admin/courses/AddNewCourse.jsx
> +      dispatch(
И почему uploadFile может addCourse action?

2022-05-21 09:54 UTC, zhumabek commented on src/components/admin/courses/Courses.jsx
> +                     card={course}
Го за card prop? Плохое название

2022-05-21 09:54 UTC, zhumabek commented on src/components/admin/courses/Courses.jsx
> +               <StyledCard key={course.id}>
Почему Card внутри StyledCard?

2022-05-21 09:54 UTC, zhumabek commented on src/store/courses-slice.jsx
> +export const uploadFile = createAsyncThunk(
Зачем uppload жана addCourse болуп жатасынар сразу эле бир экшндин ичинде суротту дагы жуктоп курсту дагы кошсонор болмок

2022-05-21 09:54 UTC, zhumabek commented on src/store/courses-slice.jsx
> +export const pagination = createAsyncThunk(
А эмне пагинацияга озунчо эндпоинт бекен ээ? По идее getAll менен чогуу болуш керек эки башка эмес

Бекендге айтып алмаштыргыла

2022-05-24 05:07 UTC, zhumabek requested changes

2022-05-24 05:07 UTC, zhumabek commented on src/components/admin/courses/AddNewCourse.jsx
> +      dispatch(getAllCourses(currentPage))
Дагы деле не то,
смотри курсту успешно кошкондон кийин анан getCourses ди чыкырышым керек да туурабы?

азыр сенде эки запрос паралельно кетип жатат анткени диспатч асинхронно иштейт синхронно эмес

еще модалка успешно курс кошулса анан жабылыш керек эгер ошибка болсо жабылбай тура бериш керек

2022-05-24 05:07 UTC, zhumabek commented on src/components/admin/courses/AddNewCourse.jsx
> +      dispatch(getAllCourses(currentPage))
Даны кайсы жерде ушундай сценарийлер болсо ондоп чыгыш керек

2022-05-24 05:07 UTC, zhumabek commented on src/pages/ADMIN/courses/courseInnerPage/CourseInstructors.jsx
> +            localStorageHelper.store('course', el.courseName)
Таак я не понял почему имя курса хранишь в локалсторедж?

2022-05-24 05:07 UTC, zhumabek commented on src/pages/ADMIN/courses/courseInnerPage/CourseInstructors.jsx
> +      dispatch(getInstructor())
Бул жерде getInstructor эмнеге керек?

2022-05-24 05:07 UTC, zhumabek commented on src/pages/ADMIN/courses/courseInnerPage/CourseStudents.jsx
> +   const course = localStorageHelper.laod('course')
Зачем это нужно?

2022-05-24 13:56 UTC, mavliuda19 commented on src/pages/ADMIN/courses/courseInnerPage/CourseInstructors.jsx
> +            localStorageHelper.store('course', el.courseName)
Bread crumbs колдонгонддо localstorage сакташ керек болду, refresh кылганда очуп кетпеш учун

2022-05-24 18:47 UTC, merged