Feature/groups admin panel
peaksoft-school/peaksoft-lms-a-web pull request #29
Opened 2022-05-24 09:47 UTC by BekembaevaSel

2022-05-25 07:21 UTC, zhumabek requested changes

2022-05-25 07:21 UTC, zhumabek commented on src/components/admin/groups/GroupCreate.jsx
> +      dispatch(
use unwrap

2022-05-25 07:21 UTC, zhumabek commented on src/components/admin/groups/GroupCreate.jsx
> +      props.setIsLoading(true)
why setIsLoading(true) maybe false?

2022-05-25 07:21 UTC, zhumabek commented on src/components/admin/groups/GroupEdit.jsx
> +      dispatch(
тоже самое use unwrap

2022-05-25 07:21 UTC, zhumabek commented on src/components/admin/groups/GroupsPanel.jsx
> +               {singleGroup && (
а зачем singleGroup && ?

2022-05-25 07:21 UTC, zhumabek commented on src/components/admin/groups/GroupsPanel.jsx
> +               {isLoading && <Notification message="Группа успешно создана" />}
нет не пойдет, используйте notification который сделал Байаалы

2022-05-25 09:17 UTC, BekembaevaSel commented on src/components/admin/groups/GroupsPanel.jsx
> +               {singleGroup && (
single group приходит с  слайса.  там он получает id определенной группы. и после action открывает модалку для редактирования

2022-05-25 14:08 UTC, BekembaevaSel commented on src/components/UI/DatePickerUi.jsx
> +                  sx={{
агай инлайн стили вообще не работают . разрешите оставить?

2022-05-26 11:35 UTC, zhumabek requested changes

2022-05-26 11:35 UTC, zhumabek commented on src/layout/header/Header.jsx
> +                  <p>Инструктор</p>
таак бул жерде алмаша турган нерсе жон эле текст экен го? а зачем анда целый компонентти дублируем?
const profileName = () => {
    switch() {
          case "INSTRUCTOR":
               return 'Instructor'
          case "STUDENT":
               return 'Teacher'     
               
    }
}

`<Container>
               <StyledProfile>
                  <BellIcon />
                  <ProfileIcon />
                  <p>{getPrifleName()}</p>
                  <LogoutButton logoutHandler={logoutHandler} />
               </StyledProfile>
               <Rectangle />
            </Container>`

2022-05-26 11:35 UTC, zhumabek commented on src/pages/INSTRUCTOR/VideoPresentationPage.jsx
> +export const VideoPresentationPage = () => {
бул вроде башка таск эле го аралашып кетиптир

2022-05-26 11:42 UTC, merged