Feature/presentation
peaksoft-school/peaksoft-lms-a-web pull request #37
Opened 2022-06-06 09:29 UTC by ric1709

2022-06-06 16:50 UTC, zhumabek requested changes

2022-06-06 16:50 UTC, zhumabek commented on src/components/UI/lessonCard/LessonCard.jsx
> +            <StyledContentItem disabled={presentation?.lessonId !== lessonId}>
бул жерде эмне болуп жатат жакшы тушунгон жокмун?

2022-06-06 16:50 UTC, zhumabek commented on src/components/instructor/lesson/presentation/PresentationModal.jsx
> +            <Input
edit  менен create экоондо тен бирдей эле форма да туурабы?
может PresentationForm деп озунчо компонент ачасын?

и ошол компонентти Create жана Edit модалдарда чакырасын

данныйлар лифтинг ап болуп чыгып турат

2022-06-07 07:24 UTC, ric1709 commented on src/components/UI/lessonCard/LessonCard.jsx
> +            <StyledContentItem disabled={presentation?.lessonId !== lessonId}>
presentation jok bolup kalsa disabled bolup kalat

2022-06-09 09:08 UTC, merged