Feature/modal
peaksoft-school/peaksoft-lms-a-web pull request #5
Opened 2022-04-29 07:16 UTC by BekembaevaSel

2022-04-29 12:23 UTC, zhumabek requested changes

2022-04-29 12:23 UTC, zhumabek commented on package.json
> +      "@date-io/dayjs": "^2.13.1",
delete dayjs + moment

2022-04-29 12:23 UTC, zhumabek commented on src/App.jsx
> +         <BasicModal
?

2022-04-29 12:23 UTC, zhumabek commented on src/App.jsx
> +            cancel="Отмена"
cancelButtonTitle
confirmButtonTitle

2022-04-29 12:23 UTC, zhumabek commented on src/components/UI/BasicModal.jsx
> +export function BasicModal(props) {
слушай а твой компонент точно reusable?  
ваш ответ?

2022-04-29 12:23 UTC, zhumabek commented on src/components/UI/BasicModal.jsx
> +               <InputContent id="modal-modal-description" sx={{ mt: 3 }}>
inline style

2022-05-03 10:25 UTC, zhumabek requested changes

2022-05-03 10:25 UTC, zhumabek commented on src/components/UI/BasicModal.jsx
> +function BasicModal(props) {
Это не basic modal а confirm modal

2022-05-03 10:25 UTC, zhumabek commented on src/components/UI/BasicModal.jsx
> +               <button type="button">{props.cancelButton}</button>
что будет если я нажму на button? ничего конечно
я же говорил что надо исправитб

2022-05-03 11:42 UTC, BekembaevaSel commented on src/components/UI/BasicModal.jsx
> +function BasicModal(props) {
Агай, у меня уже есть confirm modal.  если этот изменю будет два confirm modal-а ))) можно оставить basic?  назвала basic так как используется часто, меняется только контент

2022-05-04 14:20 UTC, merged